version: '3.9'
services:
  mariadb:
    image: mariadb:10.7.4
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./data/log/mariadb:/var/log/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    restart: unless-stopped
